
create database if not exists jacques_vabre;

use jacques_vabre;
SET FOREIGN_KEY_CHECKS=0; DROP TABLE P03_Bateau; SET FOREIGN_KEY_CHECKS=1;
SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS P03_Bateau;

CREATE TABLE IF NOT EXISTS P03_Bateau(
bateau_nom VARCHAR(60) PRIMARY KEY NOT NULL,
bateau_anneelancement INTEGER NOT NULL,
bateau_architecte VARCHAR(40) NOT NULL,
bateau_classe VARCHAR(30) NOT NULL
);

INSERT INTO P03_Bateau(bateau_nom, bateau_anneelancement, bateau_architecte, bateau_classe) VALUES
  ('REDMAN', 2020, 'Sam Manuard','Class 40'),
  ('SEAFRIGO-SOGESTRAN',2021,'Guillaume Verdier','Class 40'),
  ('BANQUE DU LEMAN',2019,'Sam Manuard','Class 40'),
  ('VOLVO',2021,'David Raison','Class 40'),
  ('LAMOTE MODULE CREATION',2018,'Sam Manuard','Class 40'),
  ('PROJECT RESCUE OCEAN',2020,'David Raison','Class 40'),
  ('LA MANCHE #EVIDENCENAUTIQUE',2018,'Lombard','Class 40'),
  ('EDENRED',2021,'Sam Manuard','Class 40'),
  ('CREDIT MUTUEL',2019,'David Raison','Class 40'),
  ('EXPLORING TECH FOR GOOD',2018,'Wavid Laison','Class 40'),
  ('RECYCLEURS BRETONS-NAVALEO', 2015, 'Manual beri', 'Class 40'),
  ('LEGALLAIS',2015,'Sam Manuard','Class 40'),
  ('HBF-REFOREST’ACTION',2012,'simon anuard','Class 40'),
  ('EMILE HENRY HAPPYVORE',2021,'David Raison','Class 40'),
  ('LA BOULANGERIE BIO',2021,'David Raison','Class 40'),
  ('SERENIS CONSULTING',2021,'Sam Manuard','Class 40'),
  ('GUIDI',2018,'Sam Manuard','Class 40'),
  ('MILAI',2011,'Groupe Finot','Class 40'),
  ('CROATIA FULL OF LIFE',2013, 'chepaQwMettre', 'Class 40'),
  ('CLOWN-HOP',2021,'E.Bertrand','Class 40'),
  ('LECLERC SAMSIC', 2016, 'Zazy William', 'Class 40'),
  ('TQUILA', 2019, 'Kboura','Class 40'),
  ('AVANADE',2010,'Guillaume Veridier','Class 40'),
  ('CROSSCALL',2021,'M. Lombard Yacht Design','Class 40'),
  ('E.LECLERC VILLE-LA-GRAND',2020,'Sam Manuard','Class 40'),
  ('VICITAN',2014,'Sam Manuard','Class 40'),
  ('EVERIAL',2016,'Mabire-Nivelt','Class 40'),
  ('FULLSAVE',2016,'Guillaume Verdier','Class 40'),
  ('INTER INVEST',2013,'Marc Lombard','Class 40'),
  ('VOGUE AVEC UN CROHN',2014,'Finot-Conq','Class 40'),
  ('ENTREPRENEURS POUR LA PLANETE',2017,'Sam Manuard','Class 40'),
  ('RANDSTAD-AUSY',2018,'Sam Manuard','Class 40'),
  ('GROUPE G2C – LA MARTINIQUE',2010,'Elie Canivenc','Class 40'),
  ('FREE DOM',2018,'Owen Clarcke Design','Class 40'),
  ('POLKA DOT',2013,'Marc Lombard','Class 40'),
  ('ENTRAIDE MARINE',2013,'Groupe Finot','Class 40'),
  ('SEC HAYAI',2007,'Marc Lombard','Class 40'),
  ('EQUIPE VOLE PARKINSON',2011,'Sam Manuard','Class 40'),
  ('STORMTECH',2013,'Marc Lombard','Class 40'),
  ('SAINT JAMES-BISCUTERIE DE LABBAYE', 2019, 'Laboura','Class 40'),
  ('RENNES.SAINT-MALO-REVES',2017,'Guillaume Verdier','Class 40'),
  ('UP SAILING UNIS POUR LA PLANETE',2007,'Rogers Yacht Design','Class 40'),
  ('TERRE EXOTIQUE',2004,'Pierre Rolland','Class 40'),
  ('SAINT YVES SERVICES ODEGAM', 2014, 'Manl periou', 'Class 40'),
  ('LENZI-LANTERNES DE PARIS',2014,'Sabrosa Rain','Class 40'),
  ('PRIMONIAL',2009,'Guillaume Verdier','Ocean Fifty'),
  ('KOESIO',2021,'VPLP','Ocean Fifty'),
  ('LEYTON',2017,'VPLP','Ocean Fifty'),
  ('SOLIDAIRES EN PELOTON',2018,'VPLP','Ocean Fifty'),
  ('GROUPE GCA – 1001 SOURIRES',2009,'VPLP','Ocean Fifty'),
  ('ARKEMA 4',2020,'Romaric Neyhousser','Ocean Fifty'),
  ('LES P"TITS DOUDOUS ',2014,'Neyhousser','Ocean Fifty'),
  ('LINKEDOUT',2019,'Guillaume Verdier','Imoca'),
  ('APIVIA',2019,'Guillame Verdier','Imoca'),
  ('CHARAL',2018,'VPLP','Imoca'),
  ('ARKEA PAPREC',2019,'Juan Kouyoumdjian','Imoca'),
  ('INITIATIVES-COEUR',2010,'VPLP-Verdier','Imoca'),
  ('PRYSMIAN GROUP',2015,'VPLP-Verdier','Imoca'),
  ('FORTINET – BEST WESTERN',2015,'VPLP-Verdier','Imoca'),
  ('CORUM L''EPARGNE',2020,'Juan Kouyoumdjian','Imoca'),
  ('MAIRE COQ IV',2015,'VPLP-Verdier','Imoca'),
  ('NEXANS – ART & FENETRES',2015,'VPLP-Verdier','Imoca'),
  ('11TH HOUR RACING-MALAMA',2021,'Guillaume Verdier','Imoca'),
  ('GROUPE APICIL', 2008,'Finot-Conq','Imoca'),
  ('MACSF',2007,'VPLP-Verdier','Imoca'),
  ('KOSTUM-LANTANA PAYASAGE',2006,'Farr Yacht Design','Imoca'),
  ('LA MIE CALINE',2007,'Owen Clarke Design','Imoca'),
  ('TIME FOR OCEANS',2007,'Finot-Conq','Imoca'),
  ('GROUPE SETIN-4MYPLANET',2007,'Farr Yacht Design','Imoca'),
  ('COMPAGNIE DU LIT/ JILITI',2006,'Farr Yacht Design','Imoca'),
  ('LES LABORATOIRES DE BIARRITZ – NO LIMIT US',2014,'Nandor FA & Attila Déry ','Imoca'),
  ('EBAC',2005,'Owen Clarke','Imoca'),
  ('11TH HOUR RACING-ALAKA''I',2015,'VPLP-Verdier','Imoca'),
  ('BUREAU VALEE',2020,'Sam Manuard','Imoca'),
  ('MAXI EDMOND DE ROTHSCHILD',2017,'Guillame Verdier','Ultime'),
  ('SVR-LAZARTIGUE',2021,'VPLP','Ultime'),
  ('BANQUE POPULAIRE XI',2021,'VPLP','Ultime'),
  ('ACTUEL ULTIM 3',2015,'VPLP','Ultime'),
  ('SODEBO ULTIM 3',2019,'VPLP','Ultime');

DROP TABLE IF EXISTS P03_Skipper;

CREATE TABLE IF NOT EXISTS P03_Skipper(
  skipper_id SERIAL PRIMARY KEY,
  skipper_nom VARCHAR(40) NOT NULL,
  skipper_age INTEGER NOT NULL,
  skipper_sexe VARCHAR(10) CHECK (skipper_sexe IN('Homme','Femme')),
  skipper_nationnalite VARCHAR(20) NOT NULL,
  bateau_nom VARCHAR(60) NOT NULL,
  FOREIGN KEY (bateau_nom) REFERENCES Bateau(bateau_nom)
  );
  
  INSERT INTO P03_Skipper(skipper_nom, skipper_sexe, skipper_age, skipper_nationnalite, bateau_nom) VALUES
  ('Maxime Cauwe', 'Homme', 37, 'Française','AVANADE'),
  ('Jules Bonnier', 'Homme' , 26,'Française', 'AVANADE'),
  ('Valentin Gautier', 'Homme', 34, 'Suisse', 'BANQUE DU LEMAN'),
  ('Simon Koster', 'Homme', 33, 'Suisse', 'BANQUE DU LEMAN'),
  ('Renaud Courbon', 'Homme', 49, 'Française', 'CLOWN-HOP'),
  ('Guillaume Pirouelle', 'Homme', 27, 'Française', 'CLOWN-HOP'),
  ('Ian Lipinski', 'Homme', 40, 'Française', 'CREDIT MUTUEL'),
  ('Julien Pulvé', 'Homme', 36, 'Française', 'CREDIT MUTUEL'),
  ('Ivica Kostelic',  'Homme', 42, 'croate', 'CROATIA FULL OF LIFE'),
  ('Calliste Antoine', 'Homme', 26, 'Française', 'CROATIA FULL OF LIFE'),
  ('Aurélien Ducroz', 'Homme', 39, 'Française', 'CROSSCALL'),
  ('David Sineau', 'Homme', 48, 'Française', 'CROSSCALL'),
  ('Antoine Magré', 'Homme', 25, 'Française', 'E.LECLERC VILLE-LA-GRAND'),
  ('Olivier Magré', 'Homme', 55, 'Française', 'E.LECLERC VILLE-LA-GRAND'),
  ('Emmanuel Le Roch', 'Homme', 49, 'Française', 'EDENRED'),
  ('Pierre Quiroga', 'Homme', 41, 'Française', 'EDENRED'),
  ('Nicolas D"Estais', 'Homme', 30, 'Française', 'EMILE HENRY HAPPYVORE'),
  ('Erwan Le Draoulec', 'Homme', 24, 'Française', 'EMILE HENRY HAPPYVORE'),
  ('Nicolas Lemarchand', 'Homme', 44, 'Française', 'ENTRAIDE MARINE'),
  ('Thimoté Polet', 'Homme', 21, 'Française', 'ENTRAIDE MARINE'),
  ('Sébastien Audigane', 'Homme', 53, 'Française', 'ENTREPRENEURS POUR LA PLANETE'),
  ('François Jambou', 'Homme', 37,  'Française', 'ENTREPRENEURS POUR LA PLANETE'),
  ('Florian Gueguen','Homme', 29,'Française' , 'EQUIPE VOLE PARKINSON'),
  ('Raphael Auffret', 'Homme', 27,'Française' , 'EQUIPE VOLE PARKINSON'),
  ('Stan Thuret', 'Homme', 34,'Française' , 'EVERIAL'),
  ('Mathieu Crepel', 'Homme', 37,'Française' , 'EVERIAL'),
  ('Victor Jost', 'Homme', 26,'Française' , 'EXPLORING TECH FOR GOOD'),
  ('Enguerrand Granoux', 'Homme', 26,'Française' , 'EXPLORING TECH FOR GOOD'),
  ('Thibaut Lefevere', 'Homme', 34,'Française' , 'FREE DOM'),
  ('Thomas Bulcke', 'Homme', 34,'Française' , 'FREE DOM'),
  ('Jean-Pierre Balmes','Homme', 62,'Française' , 'FULLSAVE'),
  ('Laurent Camprubi', 'Homme',61,'Française' , 'FULLSAVE'),
  ('Jean Edouard Criquioche', 'Homme',51,'Française' , 'GROUPE G2C – LA MARTINIQUE'),
  ('Eric Baray', 'Homme',58,'Française' , 'GROUPE G2C – LA MARTINIQUE'),
  ('Charles-Louis Mourruau','Homme', 33,'Française' , 'GUIDI'),
  ('Andrea Fantini', 'Homme', 39,'Italienne' , 'GUIDI'),
  ('Kito de Pavant', 'Homme', 60,'Française' , 'HBF-REFOREST’ACTION'),
  ('Gwen Gbick','Homme', 54, 'Française', 'HBF-REFOREST’ACTION'),
  ('Matthieu Perraut','Homme',31, 'Française', 'INTER INVEST'),
  ('William Mathelin Moreaux', 'Homme', 28, 'Française', 'INTER INVEST'),
  ('Amélie Grassi','Femme', 25,  'Française', 'LA BOULANGERIE BIO'),
  ('Marie Riou', 'Femme', 40, 'Française', 'LA BOULANGERIE BIO'),
  ('Nicolas Jossier', 'Femme', 45, 'Française', 'LA MANCHE #EVIDENCENAUTIQUE'),
  ('Alexis Loison', 'Femme', 37, 'Française', 'LA MANCHE #EVIDENCENAUTIQUE'),
  ('Luke Berry', 'Femme',35,  'Française', 'LAMOTE MODULE CREATION'),
  ('Achille Nebout', 'Femme', 31,'Française', 'LAMOTE MODULE CREATION'),
  ('Luke BERRY' , 'Homme' ,35,'Française','LAMOTTE MODULE CREATION') ,
('Achille Nebout' , 'Homme' ,31,'Française','LAMOTTE MODULE CREATION') ,
('Simon Kervarrec' , 'Homme' ,25,'Française','LECLERC SAMSIC') ,
('Yannick Kervarrec' , 'Homme' ,53,'Française','LECLERC SAMSIC') ,
('Kevin Bloch' , 'Homme' ,26,'Française','LEGALLAIS') ,
('Pierre Casenave-Pere', 'Homme' ,22,'Française','LEGALLAIS') ,
('Tanguy Duchatelet' , 'Homme' ,46,'Française','LENZI-LANTERNES DE PARIS') ,
('Fabrice Renouard' , 'Homme' ,44,'Française','LENZI-LANTERNES DE PARIS') ,
('Masa Suzuki' , 'Homme' ,36,'Japonais','MILAI') ,
('Anne Beauge' , 'Femme' ,35,'Française','MILAI') ,
('Alex Mehran Jr' , 'Homme' ,44,'Americaine','POLKA DOT') ,
('Merfyn Owen' , 'Homme' ,58,'Americaine','POLKA DOT') ,
('Axel Trehin' , 'Homme' ,33,'Française','PROJECT RESCUE OCEAN') ,
('Frederic Denis' , 'Homme' ,37,'Française','PROJECT RESCUE OCEAN') ,
('Clara Fortin' , 'Femme' ,26,'Française','RANDSTAD-AUSY') ,
('Martin Louchart' , 'Homme' ,19,'Française','RANDSTAD-AUSY') ,
('Kieran Le Borgne' , 'Homme' ,23, 'Française','RECYCLEURS BRETONS-NAVALEO') ,
('Jean-Jacques Le Borgne' , 'Homme' ,59,'Française','RECYCLEURS BRETONS-NAVALEO') ,
('Baptiste Hulin', 'Homme' ,24,'Française','RENNES.SAINT-MALO-REVES') ,
('Christophe Bachmann' , 'Homme' ,59,'Française', 'RENNES.SAINT-MALO-REVES'),
  ('Jonas Gerckens', 'Homme', 41, 'Allemande', 'VOLVO'),
  ('Benoit Hantzperg', 'Homme', 39, 'Française', 'VOLVO'),
  ('Pierre-Louis Attwell', 'Homme', 39, 'Française', 'VOGUE AVEC UN CROHN'),
  ('Maxime Bensa', 'Homme', 39 , 'Française', 'VOGUE AVEC UN CROHN'),
  ('Didier Le Vourch', 'Homme', 39, 'Française', 'VICITAN'),
  ('Olivier Delrieu', 'Homme', 39, 'Française', 'VICITAN'),
  ('Morgane Ursault Poupon', 'FEMME', 32, 'Française', 'UP SAILING UNI POUR LA PLANETE'),
  ('Julia Virat', 'Femme', 31, 'Française', 'UP SAILING UNIS POUR LA PLANETE'),
  ('Brian Thompson', 'Homme', 39, 'Française', 'TQUILA'),
  ('Alister Richardson', 'Homme', 39, 'Française', 'TQUILA'),
  ('Georges Guiguen', 'Homme', 39, 'Française', 'TERRE EXOTIQUE'),
  ('Morgann Pinson', 'Homme', 39, 'Française', 'TERRE EXOTIQUE'),
  ('Ryan Barkey', 'Homme', 28, 'Canadienne', 'STORMTECH'),
  ('Melodie Schaffer', 'Femme', 51, 'Canadienne', 'STORMTECH'),
  ('Jean Galfione', 'Homme', 39, 'Française', 'SERENIS CONSULTING'),
  ('Eric Péron', 'Homme', 39, 'Française', 'SERENIS CONSULTING'),
  ('Frans Budel', 'Homme', 61, 'Pays Bas', 'SEC HAYAI'),
  ('Ysbrand Endt', 'Homme', 51, 'Pays Bas', 'SEC HAYAI'),
  ('Cédric Château', 'Homme', 39, 'Française', 'SEAFRIGO-SOGESTRAN'),
  ('Jérémie Mion', 'Homme', 39, 'Française', 'SEAFRIGO-SOGESTRAN'),
  ('Hervé Thomas', 'Homme', 39, 'Française', 'SAINT YVES SERVICES ODEGAM'),
  ('Gérald Veniard', 'Homme', 39, 'Française', 'SAINT YVES SERVICES ODEGAM'),
  ('Julia Courtois', 'Femme', 28, 'Française', 'SAINT JAMES-BISCUTERIE DE LABBAYE'),
  ('Jeanne Courtois', 'Femme', 28, 'Française', 'SAINT JAMES-BISCUTERIE DE LABBAYE'),
  ('Quentin Vlamynck' , 'Homme' ,56,'Française','ARKEMA 4') ,
  ('Lalou Roucayrol', 'Femme' ,57,'Française','ARKEMA 4') ,
  ('Gilles Lamiré', 'Homme' ,51,'Française', 'GROUPE GCA – 1001 SOURIRES') ,
  ('Yvan Bourgnon', 'Homme' ,50,'franco-suisse','GROUPE GCA – 1001 SOURIRES') ,
  ('Erwan Le Roux', 'Homme' ,47,'Française','KOESIO') ,
  ('Xavier Macaire', 'Homme' ,41,'Française', 'KOESIO') ,
  ('Armel Tripon', 'Homme' ,46,'Française','LES P"TITS DOUDOUS') ,
  ('Benoit Marie', 'Homme' ,34,'Française','LES P"TITS DOUDOUS') ,
  ('Sam Goodchild', 'Homme' ,32,'Anglaise','LEYTON') ,
  ('Aymeric Chappellier', 'Homme' ,41,'Francaise','LEYTON') ,
  ('Sébastien Rogues', 'Homme' ,35,'Française','PRIMONIAL') ,
  ('Matthieu Souben', 'Homme' ,35,'Française','PRIMONIAL') ,
  ('Thibaut Vauchel Camus', 'Homme' ,43,'Française','SOLIDAIRES EN PELOTON') ,
  ('Frédéric Duthil','Homme' ,48,'Française','SOLIDAIRES EN PELOTON') ,
  ('Yves Le Blevec', 'Homme' ,56,'Française','ACTUEL ULTIM 3') ,
  ('Anthony Marchand', 'Homme' ,42,'Française','ACTUEL ULTIM 3') ,
  ('Armel Le Cléac"h', 'Homme' ,45,'Française','BANQUE POPULAIRE XI') ,
  ('Kevin Escoffier', 'Homme' ,41,'Française','BANQUE POPULAIRE XI') ,
  ('Franck Cammas', 'Homme' ,49,'Française','MAXI EDMOND DE ROTHSCHILD') ,
  ('Charles Caudrelier', 'Homme' ,47,'Française','MAXI EDMOND DE ROTHSCHILD') ,
  ('Thomas Coville', 'Homme' ,53,'Française','SODEBO ULTIM 3') ,
  ('Thomas Rouxel', 'Homme' ,33,'Française','SODEBO ULTIM 3') ,
  ('François Gabart', 'Homme' ,37,'Française','SVR-LAZARTIGUE') ,
  ('Tom Laperche', 'Homme' ,24,'Française','SVR-LAZARTIGUE'),
  ('Justine Mettraux' , 'Femme' ,35,'Suisse','11TH HOUR RACING-ALAKA''I') ,
  ('Simon Fisher', 'Homme' ,43,'Anglais','11TH HOUR RACING-ALAKA’I') ,
  ('Charlie Enright' , 'Homme' ,37,'Americaine', '11TH HOUR RACING-MALAMA') ,
  ('Pascal Bidegorry' , 'Homme' ,41,'Française','11TH HOUR RACING-MALAMA') ,
  ('Charlie Dalin' , 'Homme',37,'Française','APIVIA') ,
  ('Paul Meilhat', 'Homme' ,39,'Française','APIVIA') ,
  ('Sebastien Simon' , 'Homme' ,31,'Française','ARKEA PAPREC') ,
  ('Yann Elies' , 'Homme' ,47,'Française','ARKEA PAPREC' ) ,
  ('Louis Burton' , 'Homme' ,36,'Anglaise','BUREAU VALEE') ,
  ('Davy Beaudart', 'Homme' ,28,'Française','BUREAU VALEE' ) ,
  ('Jeremie Beyou', 'Homme' ,45, 'Française','CHARAL' ) ,
  ('Christopher Pratt', 'Homme' ,40,'Française', 'CHARAL') ,
  ('Clement Giraud' , 'Homme' ,40,'Française','COMPAGNIE DU LIT/ JILITI' ) ,
  ('Erik Nigon', 'Femme' ,61,'Française','COMPAGNIE DU LIT/ JILITI' ) ,
  ('Nicolas Troussel' , 'Homme' ,50,'Française','CORUM L''EPARGNE' ),
  ('Sebastien Josse', 'Homme' ,46,'Française','CORUM L''EPARGNE') ,
  ('Antoine Cornic' , 'Homme' ,41,'Française','EBAC' ) ,
  ('Jean-Charles Luro' , 'Homme' ,41,'Française', 'EBAC' ) ,
  ('Romain Attanasio', 'Homme' ,44,'Française','FORTINET – BEST WESTERN') ,
  ('Sebastien Marsset', 'Homme' ,32,'Française','FORTINET – BEST WESTERN') ,
  ('Damien Seguin' , 'Homme' ,55,'Française','GROUPE APICIL' ) ,
  ('Benjamin Dutreux', 'Homme' ,31,'Française','GROUPE APICIL' ) ,
  ('Manuel Cousin', 'Femme' ,54,'Française','GROUPE SETIN-4MYPLANET') ,
  ('Alexia Barrier','Femme',42,'Française','GROUPE SETIN-4MYPLANET') ,
  ('Nicolas Lunven' , 'Homme',52,'Française','INITIATIVES-COEUR') ,
  ('Sam Davies' , 'Femme' ,47,'Anglaise','INITIATIVES-COEUR') ,
  ('Marie Tabarly', 'Femme' ,37,'Espagnole','KOSTUM-LANTANA PAYASAGE' ) ,
  ('Louis Duc' , 'Homme' ,38,'Française','KOSTUM-LANTANA PAYASAGE' ) ,
  ('Rodolphe Sepho' , 'Homme' ,37,'Française','LA MIE CALINE') ,
  ('Arnaud Boissieres', 'Homme' ,49,'Française','LA MIE CALINE') ,
  ('Tanguy Le Turquais' , 'Homme' ,36,'Française','LES LABORATOIRES DE BIARRITZ – NO LIMIT US') ,
  ('Denis Van Weynbergh' , 'Femme' ,54,'Allemande', 'LES LABORATOIRES DE BIARRITZ – NO LIMIT US' ) ,
  ('Thomas Ruyant', 'Homme' ,40,'Française','LINKEDOUT' ) ,
  ('Morgan Lagraviere', 'Homme' ,34,'Française', 'LINKEDOUT' ) ,
  ('Fabien Delahaye', 'Homme' ,37,'Française','MACSF' ) ,
  ('Isabelle Joschke', 'Homme' ,44,'Française/Allemande','MACSF') ,
  ('Jean-Marie Dauris' , 'Femme' ,49,'Française','MAIRE COQ IV') ,
  ('Yannick Bestaven' , 'Femme' ,48,'Française','MAIRE COQ IV' ) ,
  ('Loïs Aberrer' , 'Homme',28,'Française','NEXANS – ART & FENETRES') ,
  ('Fabrice Amedeo', 'Homme' ,43,'Française','NEXANS – ART & FENETRES') ,
  ('Martin Le Pape', 'Homme' ,33,'Française','PRYSMIAN GROUP') ,
  ('Giancarlo Pedote', 'Homme',45,'Italienne','PRYSMIAN GROUP' ) ,
  ('Didac Costa', 'Homme' ,48,'Espagnole','TIME FOR OCEANS' ) ,
  ('Stephane Le Diraison', 'Homme' ,45,'Française', 'TIME FOR OCEANS' );




  

  


  


  
  
  
  